# Generated by Django 3.1.3 on 2020-11-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='choice',
            field=models.CharField(choices=[('1', 'Completed'), ('2', 'Not Completed')], default='', max_length=100),
        ),
    ]
